/// A single entry in the QPACK static table.
class QpackStaticTableEntry {
  final String name;
  final String? value;
  const QpackStaticTableEntry(this.name, [this.value]);

  @override
  String toString() => value != null ? '$name: $value' : name;
}

/// QPACK static table per RFC 9204 Appendix A.
class QpackStaticTable {
  static const List<QpackStaticTableEntry> entries = [
    QpackStaticTableEntry(':authority'),
    QpackStaticTableEntry(':path', '/'),
    QpackStaticTableEntry('age', '0'),
    QpackStaticTableEntry('content-disposition'),
    QpackStaticTableEntry('content-length', '0'),
    QpackStaticTableEntry('cookie'),
    QpackStaticTableEntry('date'),
    QpackStaticTableEntry('etag'),
    QpackStaticTableEntry('if-modified-since'),
    QpackStaticTableEntry('if-none-match'),
    QpackStaticTableEntry('last-modified'),
    QpackStaticTableEntry('link'),
    QpackStaticTableEntry('location'),
    QpackStaticTableEntry('referer'),
    QpackStaticTableEntry('set-cookie'),
    QpackStaticTableEntry(':method', 'CONNECT'),
    QpackStaticTableEntry(':method', 'DELETE'),
    QpackStaticTableEntry(':method', 'GET'),
    QpackStaticTableEntry(':method', 'HEAD'),
    QpackStaticTableEntry(':method', 'OPTIONS'),
    QpackStaticTableEntry(':method', 'POST'),
    QpackStaticTableEntry(':method', 'PUT'),
    QpackStaticTableEntry(':scheme', 'http'),
    QpackStaticTableEntry(':scheme', 'https'),
    QpackStaticTableEntry(':status', '103'),
    QpackStaticTableEntry(':status', '200'),
    QpackStaticTableEntry(':status', '304'),
    QpackStaticTableEntry(':status', '404'),
    QpackStaticTableEntry(':status', '500'),
    QpackStaticTableEntry('accept-language'),
    QpackStaticTableEntry('accept-encoding', 'gzip, deflate, br'),
    QpackStaticTableEntry('accept-ranges'),
    QpackStaticTableEntry('accept'),
    QpackStaticTableEntry('access-control-allow-origin'),
    QpackStaticTableEntry('cache-control'),
    QpackStaticTableEntry('content-encoding'),
    QpackStaticTableEntry('content-type'),
    QpackStaticTableEntry('expect'),
    QpackStaticTableEntry('expires'),
    QpackStaticTableEntry('from'),
    QpackStaticTableEntry('host'),
    QpackStaticTableEntry('if-match'),
    QpackStaticTableEntry('if-range'),
    QpackStaticTableEntry('if-unmodified-since'),
    QpackStaticTableEntry('keep-alive'),
    QpackStaticTableEntry('last-event-id'),
    QpackStaticTableEntry('origin'),
    QpackStaticTableEntry('range'),
    QpackStaticTableEntry('te'),
    QpackStaticTableEntry('trailers'),
    QpackStaticTableEntry('transfer-encoding'),
    QpackStaticTableEntry('vary'),
    QpackStaticTableEntry('via'),
    QpackStaticTableEntry('access-control-allow-credentials'),
    QpackStaticTableEntry('access-control-allow-headers'),
    QpackStaticTableEntry('access-control-allow-methods'),
    QpackStaticTableEntry('access-control-expose-headers'),
    QpackStaticTableEntry('access-control-max-age'),
    QpackStaticTableEntry('access-control-request-headers'),
    QpackStaticTableEntry('access-control-request-method'),
    QpackStaticTableEntry('alt-svc'),
    QpackStaticTableEntry('connection'),
    QpackStaticTableEntry('content-security-policy'),
    QpackStaticTableEntry('early-data'),
    QpackStaticTableEntry('expect-ct'),
    QpackStaticTableEntry('forwarded'),
    QpackStaticTableEntry('pragma'),
    QpackStaticTableEntry('proxy-authenticate'),
    QpackStaticTableEntry('proxy-authorization'),
    QpackStaticTableEntry('server'),
    QpackStaticTableEntry('strict-transport-security'),
    QpackStaticTableEntry('upgrade-insecure-requests'),
    QpackStaticTableEntry('upgrade'),
    QpackStaticTableEntry('user-agent'),
    QpackStaticTableEntry('x-content-type-options'),
    QpackStaticTableEntry('x-frame-options'),
    QpackStaticTableEntry('x-xss-protection'),
    QpackStaticTableEntry(':status', '100'),
    QpackStaticTableEntry(':status', '204'),
    QpackStaticTableEntry(':status', '206'),
    QpackStaticTableEntry(':status', '302'),
    QpackStaticTableEntry(':status', '400'),
    QpackStaticTableEntry(':status', '403'),
    QpackStaticTableEntry(':status', '421'),
    QpackStaticTableEntry(':status', '425'),
    QpackStaticTableEntry(':status', '426'),
    QpackStaticTableEntry(':status', '451'),
    QpackStaticTableEntry(':method', 'PATCH'),
    QpackStaticTableEntry(':method', 'TRACE'),
    QpackStaticTableEntry(':authority', ''),
    QpackStaticTableEntry(':path', ''),
    QpackStaticTableEntry(':protocol', 'websocket'),
    QpackStaticTableEntry(':scheme', 'ftp'),
    QpackStaticTableEntry(':scheme', 'file'),
    QpackStaticTableEntry(':status', '101'),
    QpackStaticTableEntry(':status', '201'),
    QpackStaticTableEntry(':status', '301'),
    QpackStaticTableEntry(':status', '303'),
    QpackStaticTableEntry(':status', '305'),
    QpackStaticTableEntry(':status', '307'),
    QpackStaticTableEntry(':status', '308'),
    QpackStaticTableEntry(':status', '402'),
    QpackStaticTableEntry(':status', '405'),
    QpackStaticTableEntry(':status', '406'),
    QpackStaticTableEntry(':status', '407'),
    QpackStaticTableEntry(':status', '408'),
    QpackStaticTableEntry(':status', '409'),
    QpackStaticTableEntry(':status', '410'),
    QpackStaticTableEntry(':status', '411'),
    QpackStaticTableEntry(':status', '412'),
    QpackStaticTableEntry(':status', '413'),
    QpackStaticTableEntry(':status', '414'),
    QpackStaticTableEntry(':status', '415'),
    QpackStaticTableEntry(':status', '416'),
    QpackStaticTableEntry(':status', '417'),
    QpackStaticTableEntry(':status', '422'),
    QpackStaticTableEntry(':status', '423'),
    QpackStaticTableEntry(':status', '424'),
    QpackStaticTableEntry(':status', '428'),
    QpackStaticTableEntry(':status', '429'),
    QpackStaticTableEntry(':status', '431'),
    QpackStaticTableEntry(':status', '500'),
    QpackStaticTableEntry(':status', '501'),
    QpackStaticTableEntry(':status', '502'),
    QpackStaticTableEntry(':status', '503'),
    QpackStaticTableEntry(':status', '504'),
    QpackStaticTableEntry(':status', '505'),
    QpackStaticTableEntry('accept-charset'),
    QpackStaticTableEntry('accept-datetime'),
    QpackStaticTableEntry('access-control-allow-origin', '*'),
    QpackStaticTableEntry('cache-control', 'max-age=0'),
    QpackStaticTableEntry('cache-control', 'max-age=604800'),
    QpackStaticTableEntry('cache-control', 'max-age=2592000'),
    QpackStaticTableEntry('cache-control', 'no-cache'),
    QpackStaticTableEntry('cache-control', 'no-store'),
    QpackStaticTableEntry('cache-control', 'public, max-age=31536000'),
    QpackStaticTableEntry('content-encoding', 'br'),
    QpackStaticTableEntry('content-encoding', 'compress'),
    QpackStaticTableEntry('content-encoding', 'deflate'),
    QpackStaticTableEntry('content-encoding', 'gzip'),
    QpackStaticTableEntry('content-language', ''),
    QpackStaticTableEntry('content-type', 'application/dns-message'),
    QpackStaticTableEntry('content-type', 'application/javascript'),
    QpackStaticTableEntry('content-type', 'application/json'),
    QpackStaticTableEntry('content-type', 'application/x-www-form-urlencoded'),
    QpackStaticTableEntry('content-type', 'image/gif'),
    QpackStaticTableEntry('content-type', 'image/jpeg'),
    QpackStaticTableEntry('content-type', 'image/png'),
    QpackStaticTableEntry('content-type', 'text/css'),
    QpackStaticTableEntry('content-type', 'text/html; charset=utf-8'),
    QpackStaticTableEntry('content-type', 'text/plain'),
    QpackStaticTableEntry('content-type', 'text/xml'),
    QpackStaticTableEntry('forwarded', 'by'),
    QpackStaticTableEntry('forwarded', 'for'),
    QpackStaticTableEntry('forwarded', 'host'),
    QpackStaticTableEntry('forwarded', 'proto'),
    QpackStaticTableEntry('link', ''),
    QpackStaticTableEntry('location', ''),
    QpackStaticTableEntry('range', 'bytes=0-'),
    QpackStaticTableEntry(
        'strict-transport-security', 'max-age=31536000; includesubdomains'),
    QpackStaticTableEntry(
        'strict-transport-security', 'max-age=63072000; includesubdomains'),
    QpackStaticTableEntry('vary', 'accept-encoding'),
    QpackStaticTableEntry('vary', 'origin'),
    QpackStaticTableEntry('x-content-type-options', 'nosniff'),
    QpackStaticTableEntry('x-frame-options', 'deny'),
    QpackStaticTableEntry('x-frame-options', 'sameorigin'),
    QpackStaticTableEntry('x-frame-options', 'allow-from'),
    QpackStaticTableEntry('x-xss-protection', '1'),
    QpackStaticTableEntry('x-xss-protection', '1; mode=block'),
    QpackStaticTableEntry('x-xss-protection', '1; report='),
  ];

  /// Look up an entry by index (1-based per RFC 9204).
  static QpackStaticTableEntry? get(int index) {
    if (index < 1 || index > entries.length) return null;
    return entries[index - 1];
  }

  /// Find the index of a name (with optional value).
  /// Returns the 1-based index if found, null otherwise.
  static int? findIndex(String name, [String? value]) {
    for (var i = 0; i < entries.length; i++) {
      final entry = entries[i];
      if (entry.name == name) {
        if (value == null || entry.value == value) {
          return i + 1;
        }
      }
    }
    return null;
  }

  /// Total number of entries.
  static int get length => entries.length;
}
